import { useRouter } from "next/dist/client/router";
import { useState, useEffect, useRef } from "react";
import axios from "axios";
import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0";
import { Button } from "@nextui-org/react";
import { Editor } from "@tinymce/tinymce-react";
import { data } from "autoprefixer";

function articulosContent() {
  const editorRef = useRef(null);
  const { user } = useUser();
  const [data, setData] = useState("");
  const router = useRouter();
  const articulos = router.query.articulos;

  const getData = async () => {
    axios
      .get(
        "https://prodcutosjuangranel-default-rtdb.firebaseio.com/articulos/" +
          articulos +
          ".json"
      )
      .then((response) => {
        const myData = response.data;
        setData(myData);
      });
  };

  let año = new Date().getFullYear();
  let meses = new Date().getMonth();
  const months = [
    "Enero",
    "Febrero",
    "Marzo",
    "Abril",
    "Mayo",
    "Junio",
    "Julio",
    "Agostp",
    "Septiembre",
    "Octubre",
    "Noviembre",
    "Diciembre",
  ];
  const mes = months[meses];
  let dia = new Date().getDate();

  let fecha = mes + " " + dia + ", " + año;

  const [desc, setDesc] = useState("");
  const [dieta, setDieta] = useState("");
  const [propiedades, setPropiedades] = useState(fecha);
  const [imagen, setImagen] = useState("");
  const [titulo, setTitulo] = useState("");
  const [contenido, setContenido] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    setContenido(editorRef.current.getContent());

    console.log(contenido);
    fetch(
      "https://prodcutosjuangranel-default-rtdb.firebaseio.com/articulos/" +
        articulos +
        ".json",
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          desc: desc,
          dieta: dieta,
          propiedades: propiedades,
          imagen: imagen,
          titulo: titulo,
          contenido: contenido,
        }),
      }
    ).then(() => {
      console.log();
    });
  };

  useEffect(() => {
    getData();
  });

  const handleLoad = () => {
    setDesc(data.desc);
    setDieta(data.dieta);
    setImagen(data.imagen);
    setPropiedades(data.propiedades);
    setTitulo(data.titulo);
    setContenido(data.contenido);
  };

  if (user) {
    return (
      <>
        {user.email === "gerorobalino@gmail.com" ? (
          <div className="header-curso-manage">
            <Head>
              <title>{data.titulo} manage | JuanGranel</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <form
              style={{ height: "57vh" }}
              className="form-producto card card-body border-primary"
            >
              <div className="form-group input-group">
                <input
                  type="text"
                  value={desc}
                  name="categoria1"
                  placeholder="Descripción"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setDesc(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={dieta}
                  name="categoria2"
                  placeholder="Autor/a"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setDieta(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={titulo}
                  name="categoria3"
                  placeholder="Titulo"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setTitulo(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={imagen}
                  name="categoria3"
                  placeholder="Imagen"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setImagen(e.target.value);
                  }}
                />
              </div>
              <div className="btns-data">
                <Editor
                  apiKey="8idbucxvoavnyspujhmitseuzyouxgr61o97a0642h9sqqbj"
                  onInit={(evt, editor) => (editorRef.current = editor)}
                  selector="textarea#open-source-plugins"
                  plugins="print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons"
                  imagetools_cors_hosts="picsum.photos"
                  menubar="file edit view insert format tools table help"
                  toolbar="undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media template link anchor codesample | ltr rtl"
                  toolbar_sticky={true}
                  autosave_ask_before_unload={true}
                  autosave_interval="30s"
                  autosave_prefix="{path}{query}-{id}-"
                  autosave_restore_when_empty={false}
                  autosave_retention="2m"
                  image_advtab={true}
                  template_cdate_format="[Date Created (CDATE)=%m/%d/%Y =%H=M=S]"
                  template_mdate_format="[Date Modified (MDATE)=%m/%d/%Y =%H=M=S]"
                  height={600}
                  image_caption={true}
                  value={contenido}
                  onChange={(e) => {
                    setContenido(e.target.value);
                  }}
                  quickbars_selection_toolbar="bold italic | quicklink h2 h3 blockquote quickimage quicktable"
                  noneditable_noneditable_class="mceNonEditable"
                  toolbar_mode="sliding"
                  contextmenu="link image imagetools table"
                  content_style={
                    "body { font-family=elveticaArialsans-serif; font-size=4px }"
                  }
                />
                <Button
                  onClick={(e) => {
                    handleSubmit(e);
                  }}
                >
                  Enviar (doble click para confirmar)
                </Button>
                <Button
                  onClick={() => {
                    handleLoad();
                  }}
                >
                  Cargar datos del servidor
                </Button>
              </div>
            </form>

            <h1 className="titulo-articulo">{data.titulo}</h1>
            <div className="img-container-art">
              <img className="foto-producto" alt="" src={data.imagen} />
            </div>
            <p className="descripcion-art">{data.desc}</p>
            <div className="propie-art">
              <div>
                <h3>Autor</h3>
                <p>{data.dieta}</p>
              </div>
              <div>
                <h3>
                  Fecha <span>(actualizado)</span>
                </h3>
                <p>{data.propiedades}</p>
              </div>
            </div>
            <div>{data.contenido}</div>
          </div>
        ) : (
          <>
            <Head>
              <title>{data.titulo} | JuanGranel</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="propie">
              <div>
                <h3>Dietas</h3>
                <p>{data.dieta}</p>
              </div>
              <div>
                <h3>Propiedades</h3>
                <p>{data.propiedades}</p>
              </div>
            </div>
            <h1 className="titulo-producto">{data.titulo}</h1>
            <div className="img-container">
              <img className="foto-producto" alt="" src={data.imagen} />
            </div>
            <p className="descripcion-producto">{data.desc}</p>
            <Button className="btn-producto">Pedir producto</Button>
          </>
        )}
      </>
    );
  }
  return (
    <>
      <Head>
        <title>{data.titulo} | JuanGranel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="titulo-producto">{data.titulo}</h1>
      <div className="img-container">
        <img className="foto-producto" alt="" src={data.imagen} />
      </div>
      <p className="descripcion-producto">{data.desc}</p>
      <button className="btn-producto">Pedir producto</button>
    </>
  );
}

export default articulosContent;



