import { useRouter } from "next/dist/client/router";
import { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0";
import { Button } from "@nextui-org/react";
import Link from "next/link";

function CursosContent() {
  const { user } = useUser();
  const [data, setData] = useState("");
  const router = useRouter();
  const Cursos = router.query.cursos;

  const getData = async () => {
    axios
      .get(
        "https://prodcutosjuangranel-default-rtdb.firebaseio.com/productos/" +
          Cursos +
          ".json"
      )
      .then((response) => {
        const myData = response.data;
        setData(myData);
      });
  };

  const [desc, setDesc] = useState("");
  const [dieta, setDieta] = useState("");
  const [propiedades, setPropiedades] = useState("");
  const [imagen, setImagen] = useState("");
  const [titulo, setTitulo] = useState("");


  const handleSubmit = (e) => {
    e.preventDefault();

    fetch(
      "https://prodcutosjuangranel-default-rtdb.firebaseio.com/productos/" +
        Cursos +
        ".json",
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          desc: desc,
          dieta: dieta,
          propiedades: propiedades,
          imagen: imagen,
          titulo: titulo,
        }),
      }
    ).then(() => {
      console.log();
    });
  };

  useEffect(() => {
    getData();
  });

  const handleLoad = () => {
    setDesc(data.desc);
    setDieta(data.dieta);
    setImagen(data.imagen);
    setPropiedades(data.propiedades);
    setTitulo(data.titulo);
  };

  if (user) {
    return (
      <>
        {user.email === "gerorobalino@gmail.com" ? (
          <div className="header-curso-manage">
            <Head>
              <title>{data.titulo} manage | Irina Pontón</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <form
              onSubmit={handleSubmit}
              style={{ height: "57vh" }}
              className="form-producto card card-body border-primary"
            >
              <div className="form-group input-group">
                <input
                  type="text"
                  value={desc}
                  name="categoria1"
                  placeholder="Descripción"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setDesc(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={dieta}
                  name="categoria2"
                  placeholder="Dieta"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setDieta(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={propiedades}
                  name="categoria3"
                  placeholder="Propiedades"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setPropiedades(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={titulo}
                  name="categoria3"
                  placeholder="Titulo"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setTitulo(e.target.value);
                  }}
                />
              </div>
              <div className="form-group input-group">
                <input
                  type="text"
                  value={imagen}
                  name="categoria3"
                  placeholder="Imagen"
                  className="input-news"
                  autoComplete="off"
                  onChange={(e) => {
                    setImagen(e.target.value);
                  }}
                />
              </div>
              <div className="btns-data">
                <Button
                  onClick={(e) => {
                    handleSubmit(e);
                  }}
                >
                  Enviar
                </Button>
                <Button
                  onClick={() => {
                    handleLoad();
                  }}
                >
                  Cargar datos del servidor
                </Button>
              </div>
            </form>

            <h1 className="titulo-producto">{data.titulo}</h1>
            <div className="img-container">
              <img className="foto-producto" alt="" src={data.imagen} />
            </div>
            <p className="descripcion-producto">{data.desc}</p>
            <Link href="/pedir">
              <button className="btn-producto">Pedir producto</button>
            </Link>
            <h1 className="caracteristicas-titulo">Caracteristicas</h1>
            <div className="propie">
              <div>
                <h3>Dietas</h3>
                <p>{data.dieta}</p>
              </div>
              <div>
                <h3>Propiedades</h3>
                <p>{data.propiedades}</p>
              </div>
              <div>
                <h3>Recetas</h3>
                <p>{data.propiedades}</p>
              </div>
            </div>
          </div>
        ) : (
          <>
            <Head>
              <title>{data.titulo} | Irina Pontón</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="propie">
              <div>
                <h3>Dietas</h3>
                <p>{data.dieta}</p>
              </div>
              <div>
                <h3>Propiedades</h3>
                <p>{data.propiedades}</p>
              </div>
            </div>
            <h1 className="titulo-producto">{data.titulo}</h1>
            <div className="img-container">
              <img className="foto-producto" alt="" src={data.imagen} />
            </div>
            <p className="descripcion-producto">{data.desc}</p>
            <Button className="btn-producto">Pedir producto</Button>
          </>
        )}
      </>
    );
  }
  return (
    <>
      <Head>
        <title>{data.titulo} | Irina Pontón</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="titulo-producto">{data.titulo}</h1>
      <div className="img-container">
        <img className="foto-producto" alt="" src={data.imagen} />
      </div>
      <p className="descripcion-producto">{data.desc}</p>
      <button className="btn-producto">Pedir producto</button>
    </>
  );
}

export default CursosContent;
