import Head from "next/head";
import styles from "../styles/Home.module.css";
import { init, send } from "emailjs-com";
import React, { useState } from "react";
import { Input } from "reactstrap";
import logo from "../public/img/contacto.png";
import Image from "next/image";
import { Button } from "@nextui-org/react";
//import "../js/validar";

init("user_aUU0Vn7SifIuuMMkkLn9o");

export default function Contacto() {
  const [toSend, setToSend] = useState({
    from_name: "",
    to_name: "",
    message: "",
    reply_to: "",
  });

  const onSubmit = (e) => {
    e.preventDefault();

    send(
      "gmail_mensaje",
      "template_u60fnwe",
      toSend,
      "user_aUU0Vn7SifIuuMMkkLn9o"
    )
      .then((response) => {
        console.log("SUCCESS!", response.status, response.text);
      })
      .catch((err) => {
        console.log("FAILED...", err);
      });
  };

  const handleChange = (e) => {
    setToSend({ ...toSend, [e.target.name]: e.target.value });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Contacto | Irna Pontón</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="header-news">
        <div
          style={{
            height: "7vw",
            position: "absolute",
            top: "25%",
            left: "50%",
            transform: "translateX(-50%)",
            width: "10vw",
            zIndex: "12",
          }}
        >
          <Image src={logo} alt="" layout="fill" objectFit="contain" />
        </div>
        <div className="overly-header"></div>
      </div>
      <div className="form z-index">
        <form onSubmit={onSubmit}>
          <Input
            autoComplete="off"
            className="input-news"
            id="fromName"
            type="text"
            name="from_name"
            placeholder="Tu nombre (obligatorio)"
            color="default"
            value={toSend.from_name}
            onChange={handleChange}
          />
          <Input
            autoComplete="off"
            className="input-news"
            type="text"
            name="to_name"
            placeholder="Nombre al que se dirige"
            value={toSend.to_name}
            onChange={handleChange}
          />
          <Input
            autoComplete="off"
            className="input-news"
            id="mensaje"
            type="text"
            name="message"
            placeholder="Tu mensaje (obligatorio)"
            value={toSend.message}
            onChange={handleChange}
          />
          <Input
            autoComplete="off"
            className="input-news"
            id="email"
            type="text"
            name="reply_to"
            placeholder="Tu email (obligatorio)"
            value={toSend.reply_to}
            onChange={handleChange}
          />
          <Button type="submit" id="btn-contact">
            Enviar
          </Button>
        </form>
      </div>
    </div>
  );
}
