import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button } from "@nextui-org/react";
import { useUser } from "@auth0/nextjs-auth0";
import Link from "next/link";
import router from "next/router";
import Cursos from "./catalogo";
import { Link as Scroll } from "react-scroll";

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading)
    return (
      <>
        <Head>
          <title>Inicio | JuanGranel</title>
          <meta name="description" content="Consumo consciente" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className=""></div>
      </>
    );

  if (error)
    return (
      <div>
        {error.message}
        {router.push("/")}
      </div>
    );

  if (user) {
    return (
      <div>
        <Head>
          <title>Inicio | JuanGranel</title>
          <meta name="description" content="Consumo consciente" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.container}>
          <div className="all">
            <div className="header">
              <div className="overly"></div>

              <h1 className="titulo-start">JuanGranel, <br/> consumo consciente</h1>

              <div className="contenedor-texto-home">
                <p className="texto-home">
                  Bienvenido/a al catalogo virtual de JuanGranel, In eget
                  placerat ante. Nam accumsan libero odio. Quisque convallis
                  ipsum massa, et sodales lorem interdum at. Curabitur commodo,
                  arcu eu consectetur pulvinar, sapien leo tempus diam.
                </p>
              </div>
              <Scroll
                to="cursos"
                offset={-150}
                smooth={true}
                duration={100}
                delay={0}
              >
                <Button className="btn-catalogo">Ver catálogo</Button>
              </Scroll>
            </div>
          </div>
        </main>
        <Cursos />
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>Inicio | JuanGranel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="all">
        <div className="header">
          <div className="overly"></div>
          <h1 className="titulo-start">JuanGranel,<br/> consumo consciente</h1>
          <div className="contenedor-texto-home">
            <p className="texto-home">
              Bienvenido/a al catalogo virtual de JuanGranel, In eget placerat
              ante. Nam accumsan libero odio. Quisque convallis ipsum massa, et
              sodales lorem interdum at. Curabitur commodo, arcu eu consectetur
              pulvinar, sapien leo tempus diam.
            </p>
          </div>
          <Scroll
            to="cursos"
            smooth={true}
            offset={-50}
            duration={500}
          >
            <Button className="btn-catalogo">Ver catálogo</Button>
          </Scroll>
        </div>
        <Cursos />
      </div>
    </>
  );
}
