import React from "react";
import Links from "../components/articulo_link";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import initAuth0 from "./api/utils/auth";
import { useUser } from "@auth0/nextjs-auth0";
import router from "next/router";

const ManagerA = () => {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div className=""></div>;

  if (user.email != "gerorobalino@gmail.com") {
    router.push("/");
  }

  return (
    <div className="container p-4">
      <Head>
        <title>Manager | Irina Pontón</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer theme="colored" />
      <div className="row">
        {user.email === "gerorobalino@gmail.com" ? (
          <div>
            <>
              <Links />
            </>
          </div>
        ) : (
          <></>
        )}
      </div>
    </div>
  );
};

export default ManagerA;

export const getServerSideProps = initAuth0.withPageAuthRequired();
